### ISSUE TITLE
Can't print image

### ISSUE THREAD

**Issue by thefdisk** [andresperezmelo/print_bluetooth_thermal#14]
Using example and image not printed.
Thermal Printer IWARE M58-LL
![IMG_20230726_213128](https://github.com/andresperezmelo/print_bluetooth_thermal/assets/69206586/35f96526-7c5a-4d0a-940c-0ed3361528a9)

**Comment by thefdisk** [comment]
Wow thank you for your fast response.
Okay I'll try.

**Comment by thefdisk** [comment]
Still same.
I give a width : 10 and height : 10, but still can't print an image.
![IMG_20230727_063357](https://github.com/andresperezmelo/print_bluetooth_thermal/assets/69206586/94df0e3b-b656-4035-b798-6147c9b3208b)

**Comment by andresperezmelo** [comment]
What image are you printing?

**Comment by thefdisk** [comment]
I print your logo on example.

Btw I resolve my issue with changing generator with [https://pub.dev/packages/flutter_esc_pos_utils_v2](url) , now I can print an image without issue.

Thank you for your support and your package, I appreciate it 🙇

**Comment by SamadDev** [comment]
@thefdisk 
can you explain some i got the same issue
