### ISSUE TITLE
The situation where one mobile phone is connected to two Bluetooth printers simultaneously

### ISSUE THREAD

**Issue by LeiYao123** [andresperezmelo/print_bluetooth_thermal#17]
In this situation, I want to send commands to both printers simultaneously and output paper simultaneously,
But I found that after operation, both sheets of paper will only come out of one printer (the device connected first). If you want both printers to come out of paper, you must first disconnect the previous one and then reconnect the latter one

I found that the printing plugin is also a singleton

Do you have any other suggestions, as connecting again after each disconnection will take a long time

**Comment by YahalomsGuy** [comment]
By definition, BT is a serial peep to peer connection, not a broadcast or multicast, from everything I know, it is simply impossible to connect a single bluetooth adapter in a mobile device (or wherever) to multiple ends simultaneously.

**Comment by LeiYao123** [comment]
@YahalomsGuy  One Bluetooth printer cannot be connected to two mobile phones, but one mobile phone can be connected to multiple Bluetooth printers

**Comment by andresperezmelo** [comment]
Both on Android and iOS, it's possible to connect multiple Bluetooth devices, but compatibility varies depending on the Bluetooth profiles used by the devices. Some profiles might support multiple connections, while others could have limitations on the number of simultaneous connections. Managing two Bluetooth profiles simultaneously can be more complex; in certain cases, disconnecting one and connecting another to alternate between devices might be the more feasible solution. In both systems, the choice of profiles and the handling of connections are crucial factors to consider when working with multiple Bluetooth devices.
