### ISSUE TITLE
Printers support

### ISSUE THREAD

**Issue by Blackheart8788** [andresperezmelo/print_bluetooth_thermal#44]
I like to know if this package has support for the following brands:

Phomemo, Brother, Datamax, Honeywell, and Intermec

and if not how likely is to get it.

Thanks a lot for your hard work.

**Comment by andresperezmelo** [comment]
I do not know if these printers work, label printers do not work.
In my spare time I am working to create a package for label printers.

**Comment by Blackheart8788** [comment]
Got it. Those brands have ticket printers. 
but thanks a lot for your quick response
