### ISSUE TITLE
Ticket 410mm or 4inc width

### ISSUE THREAD

**Issue by Blackheart8788** [andresperezmelo/print_bluetooth_thermal#45]
Is possible to add 4inch width to tickets for large ticket printers?

**Comment by andresperezmelo** [comment]
Yes, it is possible to add a 4-inch width to tickets for large ticket printers. The data sent to the printer are ESC POS commands and are managed using the esc_pos_utils package. This package allows you to configure the ticket width and other formatting options according to the printer's capabilities.

**Comment by Blackheart8788** [comment]
Excellent thanks
