### ISSUE TITLE
Only Prints on Print Size 1 in Bluetooth Printer PT-280

### ISSUE THREAD

**Issue by hamzamon** [andresperezmelo/print_bluetooth_thermal#48]
Hi,

I tested two Bluetooth printers, PT-280 and MPT-II on both Android and iOS devices. On iOS, both printers print all sizes (1-5). However, on Android, the PT-280 only prints in size 1 and prints empty for other sizes. Please let me know how to resolve this issue.

Update: I found that the blank print issue occurs once the default print size is changed to any other size. After, it will only print in size 1.

**Comment by andresperezmelo** [comment]
Resetting the printout when sending a new size solves the problem?

In the package there is a class  that prints various sizes, it is not documented but you can see it [here](https://github.com/andresperezmelo/print_bluetooth_thermal/blob/main/lib/post_code.dart)

_If you find this useful, let me know and I will document it._
