### ISSUE TITLE
Namespace not specified on AGP 8

### ISSUE THREAD

**Issue by westito** [andresperezmelo/print_bluetooth_thermal#53]
A problem occurred configuring project ':print_bluetooth_thermal'.
[        ] > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
[        ]    > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
[        ]      If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] > Get more help at https://help.gradle.org.
[        ] * Exception is:
[        ] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':print_bluetooth_thermal'.

**Comment by andresperezmelo** [comment]
Apparently it is in new flutter projects, I am working on the solution to update the package.

**Comment by donisaputradev** [comment]
Please tag me if this has been updated for a solution. thanks.

**Comment by masjumdotcom** [comment]
me to, same problem,
currently waiting for an update
thanks.

**Comment by andresperezmelo** [comment]
I am excited to announce that version 1.1.2 of our package is now available on [pub.dev](https://pub.dev/packages/print_bluetooth_thermal) This update addresses the issues you reported and improves overall functionality.

**Comment by masjumdotcom** [comment]
I've tried the latest update, it works well, thanks
