### ISSUE TITLE
Please make it support on IOS

### ISSUE THREAD

**Issue by ferns-it** [andresperezmelo/print_bluetooth_thermal#6]
Sir, I love this package. It is working perfectly for my project. There is one problem it is not working on iOS. Kindly make it work on iOS too..

**Comment by andresperezmelo** [comment]
Actualmente  tengo mac pero no un iPhone, cuando disponga de un iPhone trabajare en la version de IOS. estoy en proceso de compra.

**Comment by andresperezmelo** [comment]
I currently have a mac but not an iPhone, when I have an iPhone I will work on the IOS version. I am in the process of buying.

**Comment by andresperezmelo** [comment]
Currently it is already compatible with IOS
