### ISSUE TITLE
Slow Printing

### ISSUE THREAD

**Issue by Fethi-Hamdani** [andresperezmelo/print_bluetooth_thermal#9]
Everything works fine with this package except that it prints slowly using `writeBytes` also the printer keeps flashing (reconnecting) on each row printed, i guess that is the reason why it is being slow

**Comment by andresperezmelo** [comment]
It is more recommended that you use `writeBytes`, that only one print is sent, it can be the printer, the package does not work with zebra printers, but any generic printer will do.
